fiw_labels = {
    # "fiw_c_t": "Total Composite Score (0–100)",
    # "fiw_status": "Freedom Status (Free / Partly Free / Not Free)",
    "fiw_total": "Overall Freedom Score (0–100)",
    "fiw_pr_rating": "Political Rights Rating (1–7, lower = freer)",
    "fiw_cl_rating": "Civil Liberties Rating (1–7, lower = freer)",
    "fiw_pr": "Political Rights (0–40)",
    "fiw_cl": "Civil Liberties (0–60)",
    "fiw_a": "A. Electoral Process (0–12)",
    "fiw_b": "B. Political Pluralism & Participation (0–16)",
    "fiw_c": "C. Functioning of Government (0–12)",
    # "fiw_add_q": "Additional Political Rights Adjustment (–4 to 0)",
    # "fiw_add_a": "Adjusted Political Rights (0–40)",
    "fiw_d": "D. Freedom of Expression & Belief (0–16)",
    "fiw_e": "E. Associational & Organizational Rights (0–12)",
    "fiw_g": "G. Personal Autonomy & Individual Rights (0–16)",
}

ief_labels = {
    "ief_overall_score": "Overall Economic Freedom Score (0–100)",
    "ief_property_rights": "Property Rights (0–100)",
    "ief_judicial_effectiveness": "Judicial Effectiveness (0–100)",
    "ief_government_integrity": "Government Integrity (0–100)",
    "ief_tax_burden": "Tax Burden (0–100)",
    "ief_government_spending": "Government Spending (0–100)",
    "ief_fiscal_health": "Fiscal Health (0–100)",
    "ief_business_freedom": "Business Freedom (0–100)",
    "ief_labor_freedom": "Labor Freedom (0–100)",
    "ief_monetary_freedom": "Monetary Freedom (0–100)",
    "ief_trade_freedom": "Trade Freedom (0–100)",
    "ief_investment_freedom": "Investment Freedom (0–100)",
    "ief_financial_freedom": "Financial Freedom (0–100)"
}

p5d_labels = {
    "p5d_flag": "Polity Code Flag (0 = normal, 1–2 = special polity, 3 = transition)",
    "p5d_fragment": "State Fragmentation Code (0–3, higher = more territorial fragmentation)",
    "p5d_democ": "Democracy Score (0–10)",
    "p5d_autoc": "Autocracy Score (0–10)",
    "p5d_polity": "Polity Score (Democracy – Autocracy, range −10 to +10)",
    "p5d_polity2": "Polity2 Score (Revised Polity, −10 to +10, interpolated)",
    "p5d_durable": "Regime Durability (years since last regime change)",
    "p5d_xrreg": "XRREG: Regulation of Chief Executive Recruitment (0–3)",
    "p5d_xrcomp": "XRCOMP: Competitiveness of Executive Recruitment (0–3)",
    "p5d_xropen": "XROPEN: Openness of Executive Recruitment (0–4)",
    "p5d_xconst": "XCONST: Constraints on Chief Executive (1–7, higher = more constrained)",
    "p5d_parreg": "PARREG: Regulation of Political Participation (1–5)",
    "p5d_parcomp": "PARCOMP: Competitiveness of Political Participation (0–5)",
    "p5d_exrec": "EXREC: Executive Recruitment Component (0–8)",
    "p5d_exconst": "EXCONST: Executive Constraints Component (1–7)",
    "p5d_polcomp": "POLCOMP: Political Competition Component (1–10)",
    "p5d_regtrans": "Regime Transition Code (−77, −88, 0–99: special transitions or missing)",
}

efw_labels = {
    # --- Summary measures ---
    "efw_economic_freedom_summary_index": "Economic Freedom Summary Index (0–10)",
    "efw_rank": "Country Rank (1 = most free)",
    "efw_quartile": "Freedom Quartile (1 = highest freedom, 4 = lowest)",
    # --- Area 1: Size of Government ---
    "efw_1a_government_consumption": "1A. Government Consumption (0–10)",
    "efw_1b_transfers_and_subsidies": "1B. Transfers and Subsidies (0–10)",
    "efw_1c_government_investment": "1C. Government Investment (0–10)",
    "efw_1di_top_marginal_income_tax_rate": "1D(i). Top Marginal Income Tax Rate (0–10)",
    "efw_1dii_top_marginal_income_and_payroll_tax_rate": "1D(ii). Top Marginal Income + Payroll Tax Rate (0–10)",
    "efw_1d_top_marginal_tax_rate": "1D. Top Marginal Tax Rate (combined, 0–10)",
    "efw_ie_state_ownership": "1E. State Ownership of Assets (0–10)",
    "efw_1_size_of_government": "Area 1. Size of Government (0–10)",
    "efw_area_1_rank": "Area 1 Rank (lower = better)",
    # --- Area 2: Legal System & Property Rights ---
    "efw_2a_judicial_independence": "2A. Judicial Independence (0–10)",
    "efw_2b_impartial_courts": "2B. Impartial Courts (0–10)",
    "efw_2c_property_rights": "2C. Protection of Property Rights (0–10)",
    "efw_2d_military_interference": "2D. Military Interference in Rule of Law and Politics (0–10)",
    "efw_2e_legal_integrity": "2E. Integrity of the Legal System (0–10)",
    "efw_2f_contracts": "2F. Enforcement of Contracts (0–10)",
    "efw_2g_real_property": "2G. Regulation of Real Property (0–10)",
    "efw_2h_police_and_crime": "2H. Reliability of Police and Crime (0–10)",
    "efw_gender_disparity_index": "Gender Disparity Index (0–10, higher = more equality)",
    "efw_2_legal_system_property_rights_with_gender_adjustment": "Area 2. Legal System & Property Rights (gender-adjusted, 0–10)",
    "efw_2_legal_system_property_rights_no_gender_adjustment": "Area 2. Legal System & Property Rights (no gender adjustment, 0–10)",
    "efw_area_2_rank": "Area 2 Rank (lower = better)",
    # --- Area 3: Sound Money ---
    "efw_3a_money_growth": "3A. Money Growth (0–10)",
    "efw_3b_standard_deviation_of_inflation": "3B. Standard Deviation of Inflation (0–10)",
    "efw_3c_inflation": "3C. Inflation: Most Recent Year (0–10)",
    "efw_3d_foreign_currency_bank_accounts": "3D. Freedom to Own Foreign Currency Bank Accounts (0–10)",
    "efw_3_sound_money": "Area 3. Sound Money (0–10)",
    "efw_area_3_rank": "Area 3 Rank (lower = better)",
    # --- Area 4: Freedom to Trade Internationally ---
    "efw_4ai_trade_tax_revenue": "4A(i). Trade Tax Revenue (% of trade, 0–10)",
    "efw_4aii_mean_tariff_rate": "4A(ii). Mean Tariff Rate (0–10)",
    "efw_4aiii_standard_deviation_of_tariff_rates": "4A(iii). Tariff Rate Dispersion (0–10)",
    "efw_4a_tariffs": "4A. Tariffs (aggregate, 0–10)",
    "efw_4bi_non_tariff_trade_barriers": "4B(i). Non-tariff Trade Barriers (0–10)",
    "efw_4bii_costs_of_importing_and_exporting": "4B(ii). Costs of Importing and Exporting (0–10)",
    "efw_4b_regulatory_trade_barriers": "4B. Regulatory Trade Barriers (0–10)",
    "efw_4c_black_market_exchange_rates": "4C. Black Market Exchange Rates (0–10)",
    "efw_4di_financial_openness": "4D(i). Financial Openness (0–10)",
    "efw_4dii_capital_controls": "4D(ii). Capital Controls (0–10)",
    "efw_4diii_freedom_of_foreigners_to_visit": "4D(iii). Freedom of Foreigners to Visit (0–10)",
    "efw_4div_protection_of_foreign_assets": "4D(iv). Protection of Foreign-Owned Assets (0–10)",
    "efw_4d_controls_of_the_movement_of_capital_and_people": "4D. Controls of Movement of Capital and People (0–10)",
    "efw_4_freedom_to_trade_internationally": "Area 4. Freedom to Trade Internationally (0–10)",
    "efw_area_4_rank": "Area 4 Rank (lower = better)",
    # --- Area 5: Regulation ---
    "efw_5ai_ownership_of_banks": "5A(i). Ownership of Banks (0–10)",
    "efw_5aii_private_sector_credit": "5A(ii). Private Sector Credit (0–10)",
    "efw_5aiii_interest_rate_controls_negative_real_interest_rates": "5A(iii). Interest Rate Controls / Negative Real Rates (0–10)",
    "efw_5a_credit_market_regulation": "5A. Credit Market Regulation (0–10)",
    "efw_5bi_labor_regulations_and_minimum_wage": "5B(i). Labor Regulations and Minimum Wage (0–10)",
    "efw_5bii_hiring_and_firing_regulations": "5B(ii). Hiring and Firing Regulations (0–10)",
    "efw_5biii_flexible_wage_determination": "5B(iii). Flexible Wage Determination (0–10)",
    "efw_5biv_hours_regulations": "5B(iv). Hours Regulations (0–10)",
    "efw_5bv_cost_of_worker_dismissal": "5B(v). Cost of Worker Dismissal (0–10)",
    "efw_5bvi_conscription": "5B(vi). Conscription (0–10)",
    "efw_5bvii_foreign_labor": "5B(vii). Regulation of Foreign Labor (0–10)",
    "efw_5b_labor_market_regulations": "5B. Labor Market Regulations (0–10)",
    "efw_5ci_regulatory_burden": "5C(i). Regulatory Burden (0–10)",
    "efw_5cii_bureacracy_costs": "5C(ii). Bureaucracy Costs (0–10)",
    "efw_5ciii_impartial_public_administration": "5C(iii). Impartial Public Administration (0–10)",
    "efw_5civ_tax_compliance": "5C(iv). Tax Compliance (0–10)",
    "efw_5c_business_regulations": "5C. Business Regulations (0–10)",
    "efw_5di_market_openness": "5D(i). Market Openness (0–10)",
    "efw_5dii_business_permits": "5D(ii). Business Permits (0–10)",
    "efw_5diii_distorton_of_the_business_environment": "5D(iii). Distortion of the Business Environment (0–10)",
    "efw_5d_freedom_to_enter_markets_and_compete": "5D. Freedom to Enter Markets and Compete (0–10)",
    "efw_5_regulation": "Area 5. Regulation (0–10)",
    "efw_area_5_rank": "Area 5 Rank (lower = better)",
    # --- Raw data indicators ---
    # "efw_data": "Underlying data (Area 1A)",
    # "efw_data_1": "Underlying data (Area 1B)",
    # "efw_data_2": "Underlying data (Area 1C)",
    # "efw_data_3": "Underlying data (1D(i))",
    # "efw_data_4": "Underlying data (1D(ii))",
    # "efw_data_5": "Underlying data (3A)",
    # "efw_data_6": "Underlying data (3B)",
    # "efw_data_7": "Underlying data (3C)",
    # "efw_data_8": "Underlying data (4A(i))",
    # "efw_data_9": "Underlying data (4A(ii))",
    # "efw_data_10": "Underlying data (4A(iii))"
}

